// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateCategory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateRecord(arg1:number,arg2:string,arg3:number,arg4:string,arg5:string):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteRecord(arg1:number):Promise<void>;

export function ExportToCSV():Promise<string>;

export function ExportToJSON():Promise<string>;

export function GetCategories(arg1:string):Promise<Array<model.Category>>;

export function GetCategoryStats(arg1:number,arg2:number):Promise<model.CategoryStatsResponse>;

export function GetMonthSummary(arg1:number,arg2:number):Promise<model.MonthSummary>;

export function GetRecentRecords(arg1:number):Promise<Array<model.Record>>;

export function GetRecordsByMonth(arg1:number,arg2:number):Promise<Array<model.Record>>;

export function GetTrendStats(arg1:number):Promise<Array<model.MonthTrend>>;

export function ImportFromCSV():Promise<number>;

export function ImportFromJSON():Promise<number>;

export function ReorderCategories(arg1:Array<number>):Promise<void>;

export function UpdateCategory(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateRecord(arg1:number,arg2:number,arg3:number,arg4:string,arg5:string):Promise<void>;
