// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCategory'](arg1, arg2, arg3);
}

export function CreateRecord(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateRecord'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteRecord(arg1) {
  return window['go']['main']['App']['DeleteRecord'](arg1);
}

export function ExportToCSV() {
  return window['go']['main']['App']['ExportToCSV']();
}

export function ExportToJSON() {
  return window['go']['main']['App']['ExportToJSON']();
}

export function GetCategories(arg1) {
  return window['go']['main']['App']['GetCategories'](arg1);
}

export function GetCategoryStats(arg1, arg2) {
  return window['go']['main']['App']['GetCategoryStats'](arg1, arg2);
}

export function GetMonthSummary(arg1, arg2) {
  return window['go']['main']['App']['GetMonthSummary'](arg1, arg2);
}

export function GetRecentRecords(arg1) {
  return window['go']['main']['App']['GetRecentRecords'](arg1);
}

export function GetRecordsByMonth(arg1, arg2) {
  return window['go']['main']['App']['GetRecordsByMonth'](arg1, arg2);
}

export function GetTrendStats(arg1) {
  return window['go']['main']['App']['GetTrendStats'](arg1);
}

export function ImportFromCSV() {
  return window['go']['main']['App']['ImportFromCSV']();
}

export function ImportFromJSON() {
  return window['go']['main']['App']['ImportFromJSON']();
}

export function ReorderCategories(arg1) {
  return window['go']['main']['App']['ReorderCategories'](arg1);
}

export function UpdateCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2, arg3);
}

export function UpdateRecord(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateRecord'](arg1, arg2, arg3, arg4, arg5);
}
